site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - nwqueueadapters:
          - About nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib:
          - About opmonlib: packages/opmonlib/README.md
          - packages/opmonlib/Instructions-for-DAQ-module-users.md
       - readout:
          - About readout: packages/readout/README.md
          - packages/readout/Functional-elements.md
       - restcmd:
          - About restcmd: packages/restcmd/README.md
       - serialization:
          - About serialization: packages/serialization/README.md
       - timing:
          - About timing: packages/timing/README.md
       - timinglibs:
          - About timinglibs: packages/timinglibs/README.md
       - trigemu:
          - About trigemu: packages/trigemu/README.md

theme: 
   name: mkdocs
   features:
     - navigation.tabs
     - navigation.instant
