site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - daq-buildtools:
          - README: packages/daq-buildtools/README.md
          - Compiling-and-running: packages/daq-buildtools/Compiling-and-running.md
       - daq-cmake:
          - README: packages/daq-cmake/README.md
          - CmakeFunctions: packages/daq-cmake/CmakeFunctions.md
          - Creating-a-new-package: packages/daq-cmake/Creating-a-new-package.md
          - SchemaAndCodeGen: packages/daq-cmake/SchemaAndCodeGen.md
       - daq-release: packages/daq-release/README.md
       - styleguide:
          - README: packages/styleguide/README.md
       - appfwk:
          - README: packages/appfwk/README.md
          - DAQModules: packages/appfwk/DAQModules.md
          - How-to-write-your-DAQModule: packages/appfwk/How-to-write-your-DAQModule.md
          - Step-by-step-instructions-for-creating-your-own-DAQModule-package-under-v2.0.0: packages/appfwk/Step-by-step-instructions-for-creating-your-own-DAQModule-package-under-v2.0.0.md
       - cmdlib: packages/cmdlib/README.md
       - dataformats: packages/dataformats/README.md
       - dfmessages: packages/dfmessages/README.md
       - dfmodules: packages/dfmodules/README.md
       - ers: packages/ers/README.md
       - ipm: packages/ipm/README.md
       - listrev: packages/listrev/README.md
       - logging: packages/logging/README.md
       - minidaqapp:
          - README: packages/minidaqapp/README.md
          - Coordination-notes-for-v2.3.0-and-v2.4.0: packages/minidaqapp/Coordination-notes-for-v2.3.0-and-v2.4.0.md
          - Instructions-for-setting-up-a-v2.4.0-development-environment: packages/minidaqapp/Instructions-for-setting-up-a-v2.4.0-development-environment.md
          - MiniDAQApp-Diagrams: packages/minidaqapp/MiniDAQApp-Diagrams.md
          - Notes-from-meetings-and-discussions: packages/minidaqapp/Notes-from-meetings-and-discussions.md
          - Reminders-about-tests-that-we-want-to-run: packages/minidaqapp/Reminders-about-tests-that-we-want-to-run.md
          - Simple-instructions-for-running-the-app: packages/minidaqapp/Simple-instructions-for-running-the-app.md
       - nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib: packages/opmonlib/README.md
       - readout: packages/readout/README.md
       - restcmd: packages/restcmd/README.md
       - serialization: packages/serialization/README.md
       - trigemu: packages/trigemu/README.md

theme: 
   name: material
   features:
     - navigation.tabs
     - navigation.instant
