site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - logging:
          - About logging: packages/logging/README.md
          - packages/logging/Home.md
          - packages/logging/ers-conventions.md
          - packages/logging/v1.0.0-User-documentation.md
          - packages/logging/v1.0.0-documentation.md
          - packages/logging/v1.0.0-pre-release-documentation.md
       - minidaqapp:
          - About minidaqapp: packages/minidaqapp/README.md
          - packages/minidaqapp/Coordination-notes-for-v2.3.0-and-v2.4.0.md
          - packages/minidaqapp/Instructions-for-setting-up-a-v2.4.0-development-environment.md
          - packages/minidaqapp/MiniDAQApp-Diagrams.md
          - packages/minidaqapp/Notes-from-meetings-and-discussions.md
          - packages/minidaqapp/Reminders-about-tests-that-we-want-to-run.md
          - packages/minidaqapp/Simple-instructions-for-running-the-app.md
       - nwqueueadapters:
          - About nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib:
          - About opmonlib: packages/opmonlib/README.md
          - packages/opmonlib/Home.md
          - packages/opmonlib/Instructions-for-DAQ-module-users.md
       - readout:
          - About readout: packages/readout/README.md
          - packages/readout/Functional-elements.md
       - restcmd:
          - About restcmd: packages/restcmd/README.md
       - serialization:
          - About serialization: packages/serialization/README.md
       - trigemu:
          - About trigemu: packages/trigemu/README.md

theme: 
   name: mkdocs
   features:
     - navigation.tabs
     - navigation.instant
