site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - daq-buildtools:
          - About daq-buildtools: packages/daq-buildtools/README.md
          - packages/daq-buildtools/Compiling-and-running.md
       - daq-cmake:
          - About daq-cmake: packages/daq-cmake/README.md
          - packages/daq-cmake/CmakeFunctions.md
          - packages/daq-cmake/Creating-a-new-package.md
          - packages/daq-cmake/SchemaAndCodeGen.md
       - daq-release:
          - About daq-release: packages/daq-release/README.md
          - packages/daq-release/add_modules_to_pypi_repo.md
          - packages/daq-release/ci_github_action.md
          - packages/daq-release/create_release.md
          - packages/daq-release/development_workflow_gitflow.md
          - packages/daq-release/make_ups_products.md
          - packages/daq-release/publish_to_cvmfs.md
          - packages/daq-release/slides.md
          - packages/daq-release/standalone_daq_release.md
          - packages/daq-release/upsify_daq_packages.md
       - styleguide:
          - About styleguide: packages/styleguide/README.md
       - appfwk: packages/appfwk/README.md
       - cmdlib: packages/cmdlib/README.md
       - dataformats: packages/dataformats/README.md
       - dfmessages: packages/dfmessages/README.md
       - dfmodules: packages/dfmodules/README.md
       - ers: packages/ers/README.md
       - ipm: packages/ipm/README.md
       - listrev: packages/listrev/README.md
       - logging: packages/logging/README.md
       - minidaqapp: packages/minidaqapp/README.md
       - nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib: packages/opmonlib/README.md
       - readout:
          - About readout: packages/readout/README.md
       - restcmd: packages/restcmd/README.md
       - serialization: packages/serialization/README.md
       - trigemu: packages/trigemu/README.md

theme: 
   name: material
   features:
     - navigation.tabs
     - navigation.instant
