# REMINDER: USE SPACES INSTEAD OF TABS IN THIS FILE

# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: DUNE DAQ Software Documentation Home
site_description: The Official Documentation for DUNE DAQ Software Users

# Copyright
copyright: Copyright &copy; 2016 - 2021 Martin Donath

theme:
  name: material
  custom_dir: overrides
  font: false

  language: en

  features:
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

extra_javascript:
  - javascripts/base.js
  - javascripts/bootstrap.min.js
  - javascripts/jquery-1.10.2.min.js

# Plugins
plugins:
  - search

# Customization
extra:
  generator: false
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DUNE-DAQ

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Table of Contents: 
       - Overview:
          - README.md
       - Toolset:
          - daq-assettools:
          - daq-buildtools:
          - daq-cmake:
          - daq-release:
          - daqsystemtest:
          - integrationtest:
          - styleguide:
       - Core:   
          - appfwk:
          - cmdlib:
          - ers:
          - logging:
          - utilities:
             - About utilities: packages/utilities/README.md
             - packages/utilities/WorkerThread-Usage-Notes.md
       - Readout:
          - daqdataformats:
          - detchannelmaps:
          - detdataformats:
          - dpdklibs:
          - dtpcontrols:
          - dtpctrllibs:
          - fddetdataformats:
          - fdreadoutlibs:
          - flxlibs:
          - lbrulibs:
          - nddetdataformats:
          - readoutlibs:
          - readoutmodules:
          - wibmod:
             - About wibmod: packages/wibmod/README.md
             - packages/wibmod/src/WIB1/README.md
             - packages/wibmod/src/wibmod/WIB1/README.md
       - Control:
          - appdal:
          - coredal:
          - daqconf:
          - dbe:
          - nanorc:
          - restcmd:
       - Dataflow (logical):
          - dfmessages:
          - dfmodules:
          - hdf5libs:
          - timing:
          - timinglibs:
          - trigger:
       - Dataflow (physical):
          - iomanager:
          - ipm:
          - serialization:
       - Monitoring:
          - dqm:
          - erskafka:
          - kafkaopmon:
          - opmonlib:
          - rawdatautils:
       - Educational:
          - listrev:



