site_name: DUNE DAQ Software Documentation Home
site_description: The Official Documentation for DUNE DAQ Software Users
nav:
    - Home: README.md
    - Packages:
       - daq-buildtools:
          - About daq-buildtools: packages/daq-buildtools/README.md
       - daq-cmake:
          - About daq-cmake: packages/daq-cmake/README.md
       - daq-release:
          - About daq-release: packages/daq-release/README.md
          - packages/daq-release/add_modules_to_pypi_repo.md
          - packages/daq-release/ci_github_action.md
          - packages/daq-release/create_release.md
          - packages/daq-release/development_workflow_gitflow.md
          - packages/daq-release/make_ups_products.md
          - packages/daq-release/publish_to_cvmfs.md
          - packages/daq-release/slides.md
          - packages/daq-release/standalone_daq_release.md
          - packages/daq-release/upsify_daq_packages.md
       - styleguide:
          - About styleguide: packages/styleguide/README.md
       - appfwk:
          - About appfwk: packages/appfwk/README.md
          - packages/appfwk/Daq-Application.md
          - packages/appfwk/ThreadHelper-Usage-Notes.md
       - cmdlib:
          - About cmdlib: packages/cmdlib/README.md
          - packages/cmdlib/Home.md
          - packages/cmdlib/User-Guide.md
       - dataformats:
          - About dataformats: packages/dataformats/README.md
          - packages/dataformats/ComponentRequestV0.md
          - packages/dataformats/ComponentRequestV1.md
          - packages/dataformats/FragmentHeaderV1.md
          - packages/dataformats/FragmentHeaderV2.md
          - packages/dataformats/GeoIDV0.md
          - packages/dataformats/GeoIDV1.md
          - packages/dataformats/TriggerRecordHeaderDataV1.md
       - dfmessages:
          - About dfmessages: packages/dfmessages/README.md
       - dfmodules:
          - About dfmodules: packages/dfmodules/README.md
       - ers:
          - About ers: packages/ers/README.md
       - erses:
          - About erses: packages/erses/README.md
       - flxlibs:
          - About flxlibs: packages/flxlibs/README.md
          - packages/flxlibs/Checking-Debugging-Optical-Fibre-Status.md
          - packages/flxlibs/Configure-the-FELIX-card.md
          - packages/flxlibs/Enabling-links-through-software.md
          - packages/flxlibs/FELIX-Software-Suite-hack.md
          - packages/flxlibs/FELIX-assets.md
          - packages/flxlibs/Initial-setup-of-FELIX.md
          - packages/flxlibs/Local-driver.md
          - packages/flxlibs/Using-fdaq.md
       - influxopmon:
          - About influxopmon: packages/influxopmon/README.md
       - ipm:
          - About ipm: packages/ipm/README.md
       - listrev:
          - About listrev: packages/listrev/README.md
       - logging:
          - About logging: packages/logging/README.md
          - packages/logging/ers-conventions.md
       - minidaqapp:
          - About minidaqapp: packages/minidaqapp/README.md
          - packages/minidaqapp/InstructionsForCasualUsers.md
          - packages/minidaqapp/MiniDAQApp-Diagrams.md
       - nanorc:
          - About nanorc: packages/nanorc/README.md
       - nwqueueadapters:
          - About nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib:
          - About opmonlib: packages/opmonlib/README.md
          - packages/opmonlib/Instructions-for-DAQ-module-users.md
       - readout:
          - About readout: packages/readout/README.md
          - packages/readout/Functional-elements.md
       - restcmd:
          - About restcmd: packages/restcmd/README.md
       - serialization:
          - About serialization: packages/serialization/README.md
       - timing:
          - About timing: packages/timing/README.md
       - timinglibs:
          - About timinglibs: packages/timinglibs/README.md
       - trigemu:
          - About trigemu: packages/trigemu/README.md

theme: 
   name: mkdocs
   features:
     - navigation.tabs
     - navigation.instant
