site_name: DUNE DAQ Software Documentation Home
site_description: The Official Documentation for DUNE DAQ Software Users
nav:
    - Home: README.md
    - Packages:
       - serialization:
          - About serialization: packages/serialization/README.md
       - timing:
          - About timing: packages/timing/README.md
       - timinglibs:
          - About timinglibs: packages/timinglibs/README.md
       - trigemu:
          - About trigemu: packages/trigemu/README.md

theme: 
   name: mkdocs
   features:
     - navigation.tabs
     - navigation.instant
