site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - daq-buildtools:
          - About daq-buildtools: packages/daq-buildtools/README.md
          - packages/daq-buildtools/Compiling-and-running.md
       - daq-cmake:
          - About daq-cmake: packages/daq-cmake/README.md
          - packages/daq-cmake/CmakeFunctions.md
          - packages/daq-cmake/Creating-a-new-package.md
          - packages/daq-cmake/SchemaAndCodeGen.md
       - daq-release:
          - About daq-release: packages/daq-release/README.md
          - packages/daq-release/add_modules_to_pypi_repo.md
          - packages/daq-release/ci_github_action.md
          - packages/daq-release/create_release.md
          - packages/daq-release/development_workflow_gitflow.md
          - packages/daq-release/make_ups_products.md
          - packages/daq-release/publish_to_cvmfs.md
          - packages/daq-release/slides.md
          - packages/daq-release/standalone_daq_release.md
          - packages/daq-release/upsify_daq_packages.md
       - styleguide:
          - About styleguide: packages/styleguide/README.md
       - dataformats:
          - About dataformats: packages/dataformats/README.md
          - packages/dataformats/Home.md
       - dfmessages:
          - About dfmessages: packages/dfmessages/README.md
       - ipm:
          - About ipm: packages/ipm/README.md
       - minidaqapp:
          - About minidaqapp: packages/minidaqapp/README.md
          - packages/minidaqapp/Coordination-notes-for-v2.3.0-and-v2.4.0.md
          - packages/minidaqapp/Instructions-for-setting-up-a-v2.4.0-development-environment.md
          - packages/minidaqapp/MiniDAQApp-Diagrams.md
          - packages/minidaqapp/Notes-from-meetings-and-discussions.md
          - packages/minidaqapp/Reminders-about-tests-that-we-want-to-run.md
          - packages/minidaqapp/Simple-instructions-for-running-the-app.md
       - nwqueueadapters:
          - About nwqueueadapters: packages/nwqueueadapters/README.md
       - readout:
          - About readout: packages/readout/README.md
          - packages/readout/Functional-elements.md
       - serialization:
          - About serialization: packages/serialization/README.md

theme: 
   name: material
   features:
     - navigation.tabs
     - navigation.instant
