# REMINDER: USE SPACES INSTEAD OF TABS IN THIS FILE

# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: DUNE DAQ Software Documentation Home
site_description: The Official Documentation for DUNE DAQ Software Users

# Copyright
copyright: Copyright &copy; 2016 - 2021 Martin Donath

theme:
  name: material
  custom_dir: overrides
  font: false

  language: en

  features:
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

extra_javascript:
  - javascripts/base.js
  - javascripts/bootstrap.min.js
  - javascripts/jquery-1.10.2.min.js

# Plugins
plugins:
  - search

# Customization
extra:
  generator: false
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DUNE-DAQ

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Table of Contents: 
       - Overview:
          - README.md
       - Toolset:
          - daq-assettools:
             - About daq-assettools: packages/daq-assettools/README.md
          - daq-buildtools:
             - About daq-buildtools: packages/daq-buildtools/README.md
          - daq-cmake:
             - About daq-cmake: packages/daq-cmake/README.md
          - daq-release:
             - About daq-release: packages/daq-release/README.md
             - packages/daq-release/add_modules_to_pypi_repo.md
             - packages/daq-release/Build-external-packages-with-spack-in-a-work-area.md
             - packages/daq-release/Build-new-external-software-stack.md
             - packages/daq-release/ci_github_action.md
             - packages/daq-release/create_release_spack.md
             - packages/daq-release/development_workflow_gitflow.md
             - packages/daq-release/feature_branch_ci_build.md
             - packages/daq-release/nd_development_workflow_gitflow.md
             - packages/daq-release/publish_to_cvmfs.md
             - packages/daq-release/slides.md
             - packages/daq-release/team_repos.md
          - daqsystemtest:
             - About daqsystemtest: packages/daqsystemtest/README.md
             - packages/daqsystemtest/config/emulated_systems/README.md
             - packages/daqsystemtest/config/hd_coldbox_tests/README.md
             - packages/daqsystemtest/config/long_window_readout/README.md
             - packages/daqsystemtest/config/timing_systems/README.md
             - packages/daqsystemtest/integtest/README.md
          - integrationtest:
             - About integrationtest: packages/integrationtest/README.md
          - styleguide:
             - About styleguide: packages/styleguide/README.md
       - Core:   
          - appfwk:
             - About appfwk: packages/appfwk/README.md
             - packages/appfwk/Daq-Application.md
             - packages/appfwk/schema/README.md
          - cmdlib:
             - About cmdlib: packages/cmdlib/README.md
             - packages/cmdlib/Home.md
             - packages/cmdlib/User-Guide.md
          - ers:
             - About ers: packages/ers/README.md
          - logging:
             - About logging: packages/logging/README.md
             - packages/logging/ers-conventions.md
          - utilities:
             - About utilities: packages/utilities/README.md
             - packages/utilities/WorkerThread-Usage-Notes.md
       - Readout:
          - daqdataformats:
             - About daqdataformats: packages/daqdataformats/README.md
             - packages/daqdataformats/ComponentRequestV0.md
             - packages/daqdataformats/ComponentRequestV1.md
             - packages/daqdataformats/ComponentRequestV2.md
             - packages/daqdataformats/DataFormatNotes.md
             - packages/daqdataformats/FragmentHeaderV1.md
             - packages/daqdataformats/FragmentHeaderV2.md
             - packages/daqdataformats/FragmentHeaderV3.md
             - packages/daqdataformats/FragmentHeaderV4.md
             - packages/daqdataformats/GeoIDV0.md
             - packages/daqdataformats/GeoIDV1.md
             - packages/daqdataformats/SourceIDV2.md
             - packages/daqdataformats/TriggerRecordHeaderDataV1.md
             - packages/daqdataformats/TriggerRecordHeaderDataV2.md
             - packages/daqdataformats/TriggerRecordHeaderDataV3.md
          - detchannelmaps:
             - About detchannelmaps: packages/detchannelmaps/README.md
          - detdataformats:
             - About detdataformats: packages/detdataformats/README.md
          - lbrulibs:
             - About lbrulibs: packages/lbrulibs/README.md
             - packages/lbrulibs/integtest/README.md
             - packages/lbrulibs/socket-implementation.md
          - nddetdataformats:
             - About nddetdataformats: packages/nddetdataformats/README.md
          - readoutlibs:
             - About readoutlibs: packages/readoutlibs/README.md
             - packages/readoutlibs/Directory-structure.md
             - packages/readoutlibs/scripts/README.md
          - readoutmodules:
             - About readoutmodules: packages/readoutmodules/README.md
       - Control:
          - dal:
             - About dal: packages/dal/README.md
             - packages/dal/RELEASE_NOTES.md
          - daqconf:
             - About daqconf: packages/daqconf/README.md
             - packages/daqconf/ConfigDatabase.md
             - packages/daqconf/ConfigurationsForCasualUsers.md
             - packages/daqconf/InstructionsForCasualUsers.md
             - packages/daqconf/MigratingTov3_2_0Confgen.md
             - packages/daqconf/MigratingTov4_1_0Confgen.md
             - packages/daqconf/pytest/README.md
             - packages/daqconf/UpdatedIOManagerAPI.md
          - dbe:
             - About dbe: packages/dbe/README.md
          - nanorc:
             - About nanorc: packages/nanorc/README.md
             - packages/nanorc/FAQ-k8s.md
             - packages/nanorc/FAQ.md
             - packages/nanorc/integtests/README.md
             - packages/nanorc/src/nanorc/webuidata/static/vendor/jquery-machine/README.md
             - packages/nanorc/src/nanorc/webuidata/static/vendor/jstree/demo/README.md
             - packages/nanorc/src/nanorc/webuidata/static/vendor/jstree/README.md
          - restcmd:
             - About restcmd: packages/restcmd/README.md
             - packages/restcmd/scripts/README.md
       - Dataflow (logical):
          - dfmessages:
             - About dfmessages: packages/dfmessages/README.md
          - dfmodules:
             - About dfmodules: packages/dfmodules/README.md
             - packages/dfmodules/integtest/README.md
             - packages/dfmodules/python/dfmodules/tpset_demo/README.md
             - packages/dfmodules/TRB_metrics.md
          - hdf5libs:
             - About hdf5libs: packages/hdf5libs/README.md
             - packages/hdf5libs/V3FileFormatInterfaceChanges.md
          - timing:
             - About timing: packages/timing/README.md
             - packages/timing/test/Notes.md
          - timinglibs:
             - About timinglibs: packages/timinglibs/README.md
          - trigger:
             - About trigger: packages/trigger/README.md
             - packages/trigger/trigger-alg-howto.md
       - Dataflow (physical):
          - iomanager:
             - About iomanager: packages/iomanager/README.md
             - packages/iomanager/NetworkManager.md
             - packages/iomanager/Queue.md
             - packages/iomanager/Test-Applications.md
             - packages/iomanager/Updating.md
             - packages/iomanager/Using-dynamic-connection-names.md
          - ipm:
             - About ipm: packages/ipm/README.md
          - serialization:
             - About serialization: packages/serialization/README.md
       - Monitoring:
          - erskafka:
             - About erskafka: packages/erskafka/README.md
          - kafkaopmon:
             - About kafkaopmon: packages/kafkaopmon/README.md
          - opmonlib:
             - About opmonlib: packages/opmonlib/README.md
             - packages/opmonlib/Instructions-for-DAQ-module-users.md
       - Educational:
          - listrev:
             - About listrev: packages/listrev/README.md



