var searchData=
[
  ['ta_20latencies_20converter_20script_0',['TP latencies to TA latencies converter script',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2convert-tplatencies.html',1,'']]],
  ['test_20applications_1',['IOManager Test Applications',['../md__2github_2workspace_2dev__area_2sourcecode_2iomanager_2docs_2Test-Applications.html',1,'']]],
  ['testing_20status_2',['Felix Firmware Integration Testing status',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Integration-tests.html',1,'']]],
  ['tests_3',['Basic tests',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Basic-tests.html',1,'']]],
  ['textual_20database_20editor_20dbe_4',['Textual Database Editor (DBE)',['../md__2github_2workspace_2dev__area_2sourcecode_2daqconf_2docs_2TextualDBE.html',1,'']]],
  ['the_20card_5',['Enabling links and setting up the card',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Enabling-links-and-setting-the-superchunk-factor.html',1,'']]],
  ['the_20daq_20application_6',['Running the DAQ application',['../md__2github_2workspace_2dev__area_2sourcecode_2restcmd_2scripts_2README.html',1,'']]],
  ['the_20dune_20daq_20application_20framework_7',['appfwk: The DUNE DAQ Application Framework',['../md__2github_2workspace_2dev__area_2sourcecode_2appfwk_2docs_2README.html',1,'']]],
  ['the_20far_20detector_8',['fdreadoutmodules - Readout plugin collection for the far detector',['../md__2github_2workspace_2dev__area_2sourcecode_2fdreadoutmodules_2docs_2README.html',1,'']]],
  ['the_20felix_20internal_20emulator_9',['Configuring the FELIX internal emulator',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Configuring-the-EMU.html',1,'']]],
  ['the_20local_20driver_10',['What is the &quot;local&quot; driver?',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Local-driver.html',1,'']]],
  ['the_20okssystem_20package_11',['The OksSystem package',['../Sys_package.html',1,'']]],
  ['this_20repo_12',['Directory structure of this repo',['../md__2github_2workspace_2dev__area_2sourcecode_2datahandlinglibs_2docs_2Directory-structure.html',1,'']]],
  ['thu_20apr_2020_2011_3a18_3a42_20cdt_202023_13',['No Official User Documentation Has Been Written Yet (Thu Apr 20 11:18:42 CDT 2023)',['../md__2github_2workspace_2dev__area_2sourcecode_2trgdataformats_2docs_2README.html',1,'']]],
  ['timing_14',['timing',['../md__2github_2workspace_2dev__area_2sourcecode_2timing_2docs_2README.html',1,'']]],
  ['timinglibs_15',['timinglibs',['../md__2github_2workspace_2dev__area_2sourcecode_2timinglibs_2docs_2README.html',1,'']]],
  ['to_20ta_20latencies_20converter_20script_16',['TP latencies to TA latencies converter script',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2convert-tplatencies.html',1,'']]],
  ['to_20use_20em_20iomanager_20em_17',['Updating Existing Code to Use &lt;em&gt;iomanager&lt;/em&gt;',['../md__2github_2workspace_2dev__area_2sourcecode_2iomanager_2docs_2Updating.html',1,'']]],
  ['to_20write_20a_20trigger_20algorithm_18',['How to write a trigger algorithm',['../md__2github_2workspace_2dev__area_2sourcecode_2trigger_2docs_2trigger-alg-howto.html',1,'']]],
  ['todo_20list_19',['Todo List',['../todo.html',1,'']]],
  ['tools_20',['Trigger Emulation &amp; Analysis Tools',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2README.html',1,'']]],
  ['tp_20latencies_20to_20ta_20latencies_20converter_20script_21',['TP latencies to TA latencies converter script',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2convert-tplatencies.html',1,'']]],
  ['tp_20streams_22',['Processing TP Streams',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2process-tpstream.html',1,'']]],
  ['tpglibs_23',['tpglibs',['../md__2github_2workspace_2dev__area_2sourcecode_2tpglibs_2docs_2README.html',1,'']]],
  ['tpset_5fdemo_24',['tpset_demo',['../md__2github_2workspace_2dev__area_2sourcecode_2dfmodules_2python_2dfmodules_2tpset__demo_2README.html',1,'']]],
  ['trgtools_20module_25',['Python trgtools Module',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2py-trgtools.html',1,'']]],
  ['trigger_26',['trigger',['../md__2github_2workspace_2dev__area_2sourcecode_2trigger_2docs_2README.html',1,'About trigger'],['../md__2github_2workspace_2dev__area_2sourcecode_2triggeralgs_2include_2triggeralgs_2PlaneCoincidence_2README.html',1,'Plane Coincidence Trigger']]],
  ['trigger_20activity_20dump_20info_27',['Trigger Activity Dump Info',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2ta-dump.html',1,'']]],
  ['trigger_20algorithm_28',['How to write a trigger algorithm',['../md__2github_2workspace_2dev__area_2sourcecode_2trigger_2docs_2trigger-alg-howto.html',1,'']]],
  ['trigger_20candidate_20dump_20info_29',['Trigger Candidate Dump Info',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2tc-dump.html',1,'']]],
  ['trigger_20emulation_20analysis_20tools_30',['Trigger Emulation &amp; Analysis Tools',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2README.html',1,'']]],
  ['trigger_20primitive_20dump_20info_31',['Trigger Primitive Dump Info',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2tp-dump.html',1,'']]],
  ['trigger_20record_20builder_20metrics_32',['Trigger Record Builder metrics',['../md__2github_2workspace_2dev__area_2sourcecode_2dfmodules_2docs_2TRB__metrics.html',1,'']]],
  ['triggerrecordheaderdata_20v1_20deprecated_33',['TriggerRecordHeaderData v1 (Deprecated)',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2TriggerRecordHeaderDataV1.html',1,'']]],
  ['triggerrecordheaderdata_20v2_34',['TriggerRecordHeaderData v2',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2TriggerRecordHeaderDataV2.html',1,'']]],
  ['triggerrecordheaderdata_20v3_35',['TriggerRecordHeaderData v3',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2TriggerRecordHeaderDataV3.html',1,'']]],
  ['tt_20kafkaopmon_20tt_20kafka_20plugin_20for_20operational_20monitoring_36',['&lt;tt&gt;kafkaopmon&lt;/tt&gt; - Kafka plugin for Operational Monitoring',['../md__2github_2workspace_2dev__area_2sourcecode_2kafkaopmon_2docs_2README.html',1,'']]]
];
