var searchData=
[
  ['daq_20application_0',['daq application',['../md__2github_2workspace_2dev__area_2sourcecode_2appfwk_2docs_2Daq-Application.html',1,'DAQ Application'],['../md__2github_2workspace_2dev__area_2sourcecode_2restcmd_2scripts_2README.html',1,'Running the DAQ application']]],
  ['daq_20application_20framework_1',['appfwk: The DUNE DAQ Application Framework',['../md__2github_2workspace_2dev__area_2sourcecode_2appfwk_2docs_2README.html',1,'']]],
  ['daq_20c_20object_20serialization_20utilities_2',['DUNE DAQ C++ object serialization utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2serialization_2docs_2README.html',1,'']]],
  ['daq_20cmake_3',['daq-cmake',['../md__2github_2workspace_2dev__area_2sourcecode_2daq-cmake_2docs_2README.html',1,'']]],
  ['daq_20configuration_20inspector_4',['DAQ Configuration Inspector',['../md__2github_2workspace_2dev__area_2sourcecode_2daqconf_2docs_2Inspector.html',1,'']]],
  ['daq_20data_20formats_5',['daq data formats',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2README.html',1,'DUNE DAQ Data Formats'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2DataFormatNotes.html',1,'Some Notes on DAQ Data Formats']]],
  ['daq_20doxygen_20homepage_6',['DUNE DAQ Doxygen Homepage',['../index.html',1,'']]],
  ['daq_20release_7',['About daq-release',['../md_README.html',1,'']]],
  ['daqsystemtest_8',['daqsystemtest',['../md__2github_2workspace_2dev__area_2sourcecode_2daqsystemtest_2docs_2README.html',1,'']]],
  ['data_20formats_9',['data formats',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2README.html',1,'DUNE DAQ Data Formats'],['../md__2github_2workspace_2dev__area_2sourcecode_2detdataformats_2docs_2README.html',1,'DUNE Detectors Data Formats'],['../md__2github_2workspace_2dev__area_2sourcecode_2fddetdataformats_2docs_2README.html',1,'DUNE Far Detector Data Formats'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2DataFormatNotes.html',1,'Some Notes on DAQ Data Formats']]],
  ['data_20handling_20software_20and_20utilities_10',['datahandlinglibs - Generic data handling software and utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2datahandlinglibs_2docs_2README.html',1,'']]],
  ['data_20selection_20object_20definitions_20and_20fragment_20overlay_11',['Data selection object definitions and fragment overlay',['../md__2github_2workspace_2dev__area_2sourcecode_2trgdataformats_2include_2trgdataformats_2README.html',1,'']]],
  ['database_20editor_12',['DBE (DataBase Editor)',['../md__2github_2workspace_2dev__area_2sourcecode_2dbe_2docs_2README.html',1,'']]],
  ['dataflow_20messages_13',['DataFlow Messages',['../md__2github_2workspace_2dev__area_2sourcecode_2dfmessages_2docs_2README.html',1,'']]],
  ['datahandlinglibs_20generic_20data_20handling_20software_20and_20utilities_14',['datahandlinglibs - Generic data handling software and utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2datahandlinglibs_2docs_2README.html',1,'']]],
  ['dbe_20database_20editor_15',['DBE (DataBase Editor)',['../md__2github_2workspace_2dev__area_2sourcecode_2dbe_2docs_2README.html',1,'']]],
  ['definitions_20and_20fragment_20overlay_16',['Data selection object definitions and fragment overlay',['../md__2github_2workspace_2dev__area_2sourcecode_2trgdataformats_2include_2trgdataformats_2README.html',1,'']]],
  ['deprecated_17',['deprecated',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2ComponentRequestV0.html',1,'ComponentRequest v0 (Deprecated)'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2FragmentHeaderV1.html',1,'FragmentHeader v1 (Deprecated)'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2FragmentHeaderV2.html',1,'FragmentHeader v2 (Deprecated)'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2GeoIDV0.html',1,'GeoID v0 (Deprecated)'],['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2TriggerRecordHeaderDataV1.html',1,'TriggerRecordHeaderData v1 (Deprecated)']]],
  ['detector_18',['fdreadoutmodules - Readout plugin collection for the far detector',['../md__2github_2workspace_2dev__area_2sourcecode_2fdreadoutmodules_2docs_2README.html',1,'']]],
  ['detector_20data_20formats_19',['DUNE Far Detector Data Formats',['../md__2github_2workspace_2dev__area_2sourcecode_2fddetdataformats_2docs_2README.html',1,'']]],
  ['detector_20readout_20libraries_20',['fdreadoutlibs - Far Detector readout libraries',['../md__2github_2workspace_2dev__area_2sourcecode_2fdreadoutlibs_2docs_2README.html',1,'']]],
  ['detectors_20channel_20maps_21',['DUNE Detectors Channel Maps',['../md__2github_2workspace_2dev__area_2sourcecode_2detchannelmaps_2docs_2README.html',1,'']]],
  ['detectors_20data_20formats_22',['DUNE Detectors Data Formats',['../md__2github_2workspace_2dev__area_2sourcecode_2detdataformats_2docs_2README.html',1,'']]],
  ['diagram_20of_20your_20configuration_23',['Creating A Diagram of Your Configuration',['../md__2github_2workspace_2dev__area_2sourcecode_2daqconf_2docs_2ConfigPlotting.html',1,'']]],
  ['directory_20structure_20of_20this_20repo_24',['Directory structure of this repo',['../md__2github_2workspace_2dev__area_2sourcecode_2datahandlinglibs_2docs_2Directory-structure.html',1,'']]],
  ['documentation_20has_20been_20written_20yet_20thu_20apr_2020_2011_3a18_3a42_20cdt_202023_25',['No Official User Documentation Has Been Written Yet (Thu Apr 20 11:18:42 CDT 2023)',['../md__2github_2workspace_2dev__area_2sourcecode_2trgdataformats_2docs_2README.html',1,'']]],
  ['documentation_20has_20been_20written_20yet_20tue_20feb_2020_2017_3a12_3a47_20cet_202024_26',['No Official User Documentation Has Been Written Yet (Tue Feb 20 17:12:47 CET 2024)',['../md__2github_2workspace_2dev__area_2sourcecode_2daphnemodules_2docs_2README.html',1,'']]],
  ['doxygen_20homepage_27',['DUNE DAQ Doxygen Homepage',['../index.html',1,'']]],
  ['dpdk_20uio_20software_20and_20utilities_28',['dpdklibs - DPDK UIO software and utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2dpdklibs_2docs_2README.html',1,'']]],
  ['dpdklibs_20dpdk_20uio_20software_20and_20utilities_29',['dpdklibs - DPDK UIO software and utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2dpdklibs_2docs_2README.html',1,'']]],
  ['driver_30',['What is the &quot;local&quot; driver?',['../md__2github_2workspace_2dev__area_2sourcecode_2flxlibs_2docs_2Local-driver.html',1,'']]],
  ['dump_20info_31',['dump info',['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2ta-dump.html',1,'Trigger Activity Dump Info'],['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2tc-dump.html',1,'Trigger Candidate Dump Info'],['../md__2github_2workspace_2dev__area_2sourcecode_2trgtools_2docs_2tp-dump.html',1,'Trigger Primitive Dump Info']]],
  ['dune_20daq_20application_20framework_32',['appfwk: The DUNE DAQ Application Framework',['../md__2github_2workspace_2dev__area_2sourcecode_2appfwk_2docs_2README.html',1,'']]],
  ['dune_20daq_20c_20object_20serialization_20utilities_33',['DUNE DAQ C++ object serialization utilities',['../md__2github_2workspace_2dev__area_2sourcecode_2serialization_2docs_2README.html',1,'']]],
  ['dune_20daq_20data_20formats_34',['DUNE DAQ Data Formats',['../md__2github_2workspace_2dev__area_2sourcecode_2daqdataformats_2docs_2README.html',1,'']]],
  ['dune_20daq_20doxygen_20homepage_35',['DUNE DAQ Doxygen Homepage',['../index.html',1,'']]],
  ['dune_20detectors_20channel_20maps_36',['DUNE Detectors Channel Maps',['../md__2github_2workspace_2dev__area_2sourcecode_2detchannelmaps_2docs_2README.html',1,'']]],
  ['dune_20detectors_20data_20formats_37',['DUNE Detectors Data Formats',['../md__2github_2workspace_2dev__area_2sourcecode_2detdataformats_2docs_2README.html',1,'']]],
  ['dune_20far_20detector_20data_20formats_38',['DUNE Far Detector Data Formats',['../md__2github_2workspace_2dev__area_2sourcecode_2fddetdataformats_2docs_2README.html',1,'']]],
  ['dunedaq_39',['utilities: Utility classes for dunedaq',['../md__2github_2workspace_2dev__area_2sourcecode_2utilities_2docs_2README.html',1,'']]]
];
