# This is a basic workflow to help you get started with Actions

name: Build docs

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
    paths-ignore:
      - 'docs/packages/**'
      - 'mkdocs.yml'
      - '.github/**'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'docs/packages/**'
      - 'mkdocs.yml'
      - '.github/**'
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout docs
        uses: actions/checkout@v2
        with:
            path: docs

      # Blow away docs/pacakges and mkdocs.yml, run build script and commit.
      - name: prepare for running "bin/the_final_markdown.sh"
        run: |
            cd $GITHUB_WORKSPACE/docs
            rm -rf docs/packages mkdocs.yml
            pip install -r docs/requirements.txt
            bin/the_final_markdown.sh | tee $GITHUB_WORKSPACE/build_log.txt
            date >> $GITHUB_WORKSPACE/build_log.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated"
            git push

      - name: upload build log
        uses: actions/upload-artifact@v2
        with:
          name: docs build log
          path: ${{ github.workspace }}/build_log.txt
