name: Hello world

on:
  schedule:
    - cron: "50 17 * * *"

  workflow_dispatch:
    inputs:
      tag-prefix:
        description: 'nightly tag prefix (also used for output container tag)'
        default: ''
      feature-branch:
        description: 'feature branch to be used across all DAQ repos wherever possible.'
        default: develop
      cvmfs-deployment:
        description: 'whether to deploy the release to cvmfs'
        default: 'no'
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'

jobs:
  make_tags:
    name: create base tag and detector tag
    runs-on: ubuntu-latest
    outputs:
      base_tag: ${{ steps.create_tags.outputs.base_tag }} 
      detector_tag: ${{ steps.create_tags.outputs.detector_tag }} 
    defaults:
      run:
        shell: bash
    steps:
    - id: create_tags
      run: |
        date_tag=$(date +%y%m%d)

        # Use GitHub input if provided, else default to N
        prefix="${{ github.event.inputs.tag-prefix }}"
        if [[ -z "$prefix" ]]; then
          prefix="N"
        fi

        base_tag="${prefix}B_DEV_${date_tag}_A9"
        detector_tag="${prefix}FD_DEV_${date_tag}_A9"

        echo "base_tag=$base_tag" >> "$GITHUB_OUTPUT"
        echo "detector_tag=$detector_tag" >> "$GITHUB_OUTPUT"
        echo "detector_tag=$detector_tag" >> "$GITHUB_ENV"
        echo "base_tag=$base_tag"
        echo "detector_tag=$detector_tag"
        date --utc
        echo "Hello, world!"
    # - uses: cvmfs-contrib/github-action-cvmfs@v5
    #   with:
    #     cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'
    # - name: Check tag on cvmfs
    #   run: |
    #     if [[ -d /cvmfs/dunedaq-development.opensciencegrid.org/nightly/${detector_tag} ]]; then
    #       echo "ERROR: Build area $detector_tag already exists on CVMFS."
    #       exit 1
    #     fi
